reviews:
  namespace: student27-bookinfo-prd
  image: ghcr.io/bordee2000/bookinfo-reviews
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.prd.opsta.net
  path: "/student27/reviews(/|$)(.*)"
  serviceType: ClusterIP